package proyectoBibliotecaHibernate;
// Generated 22-ene-2017 14:46:13 by Hibernate Tools 4.3.1.Final

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private int isbn;
	private String titulo;
	private String autor;
	private String editorial;
	private Integer anyopublicacion;
	private Boolean edicionlujo;

	public Libro() {
	}

	public Libro(int isbn) {
		this.isbn = isbn;
	}

	public Libro(int isbn, String titulo, String autor, String editorial, Integer anyopublicacion,
			Boolean edicionlujo) {
		this.isbn = isbn;
		this.titulo = titulo;
		this.autor = autor;
		this.editorial = editorial;
		this.anyopublicacion = anyopublicacion;
		this.edicionlujo = edicionlujo;
	}

	public int getIsbn() {
		return this.isbn;
	}

	public void setIsbn(int isbn) {
		this.isbn = isbn;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Integer getAnyopublicacion() {
		return this.anyopublicacion;
	}

	public void setAnyopublicacion(Integer anyopublicacion) {
		this.anyopublicacion = anyopublicacion;
	}

	public Boolean getEdicionlujo() {
		return this.edicionlujo;
	}

	public void setEdicionlujo(Boolean edicionlujo) {
		this.edicionlujo = edicionlujo;
	}

}
