package proyectoBibliotecaHibernate;
// Generated 22-ene-2017 14:46:13 by Hibernate Tools 4.3.1.Final

/**
 * Revista generated by hbm2java
 */
public class Revista implements java.io.Serializable {

	private int issn;
	private String titulo;
	private String editorial;
	private Integer anyopublicacion;
	private Integer mespublicacion;

	public Revista() {
	}

	public Revista(int issn) {
		this.issn = issn;
	}

	public Revista(int issn, String titulo, String editorial, Integer anyopublicacion, Integer mespublicacion) {
		this.issn = issn;
		this.titulo = titulo;
		this.editorial = editorial;
		this.anyopublicacion = anyopublicacion;
		this.mespublicacion = mespublicacion;
	}

	public int getIssn() {
		return this.issn;
	}

	public void setIssn(int issn) {
		this.issn = issn;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	public Integer getAnyopublicacion() {
		return this.anyopublicacion;
	}

	public void setAnyopublicacion(Integer anyopublicacion) {
		this.anyopublicacion = anyopublicacion;
	}

	public Integer getMespublicacion() {
		return this.mespublicacion;
	}

	public void setMespublicacion(Integer mespublicacion) {
		this.mespublicacion = mespublicacion;
	}

}
