package ejerciciospropuestos_4_9_1;
// Generated 17-ene-2017 20:44:11 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name = "tareas", schema = "public")
public class Tareas implements java.io.Serializable {

	private String codigo;
	private Date fecha;
	private String descripcion;
	private Boolean completada;

	public Tareas() {
	}

	public Tareas(String codigo) {
		this.codigo = codigo;
	}

	public Tareas(String codigo, Date fecha, String descripcion, Boolean completada) {
		this.codigo = codigo;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.completada = completada;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "completada")
	public Boolean getCompletada() {
		return this.completada;
	}

	public void setCompletada(Boolean completada) {
		this.completada = completada;
	}

}
