package ejerciciospropuestos_4_8_3;
// Generated 17-ene-2017 20:13:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Actores generated by hbm2java
 */
public class Actores implements java.io.Serializable {

	private String id;
	private String nombre;
	private String apellidos;
	private Set serieses = new HashSet(0);

	public Actores() {
	}

	public Actores(String id) {
		this.id = id;
	}

	public Actores(String id, String nombre, String apellidos, Set serieses) {
		this.id = id;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.serieses = serieses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set serieses) {
		this.serieses = serieses;
	}

}
