package ejerciciospropuestos_4_8_3;
// Generated 17-ene-2017 20:13:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cadenas generated by hbm2java
 */
public class Cadenas implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private Set serieses = new HashSet(0);

	public Cadenas() {
	}

	public Cadenas(String codigo) {
		this.codigo = codigo;
	}

	public Cadenas(String codigo, String nombre, Set serieses) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.serieses = serieses;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getSerieses() {
		return this.serieses;
	}

	public void setSerieses(Set serieses) {
		this.serieses = serieses;
	}

}
