package ejerciciospropuestos_4_8_3;
// Generated 17-ene-2017 20:13:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Series generated by hbm2java
 */
public class Series implements java.io.Serializable {

	private int codigo;
	private Cadenas cadenas;
	private String nombre;
	private Integer duracion;
	private Set actoreses = new HashSet(0);

	public Series() {
	}

	public Series(int codigo) {
		this.codigo = codigo;
	}

	public Series(int codigo, Cadenas cadenas, String nombre, Integer duracion, Set actoreses) {
		this.codigo = codigo;
		this.cadenas = cadenas;
		this.nombre = nombre;
		this.duracion = duracion;
		this.actoreses = actoreses;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Cadenas getCadenas() {
		return this.cadenas;
	}

	public void setCadenas(Cadenas cadenas) {
		this.cadenas = cadenas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public Set getActoreses() {
		return this.actoreses;
	}

	public void setActoreses(Set actoreses) {
		this.actoreses = actoreses;
	}

}
